[terminal.shell]
program = "wsl"

[window]
decorations = "Full"
startup_mode = "Windowed"
dynamic_title = true
padding = { x = 10, y = 10 }
dynamic_padding = false
dimensions = { columns = 165, lines = 39 }

[env]
TERM = "xterm-256color"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"
